### ISSUE TITLE
Improve visibility of arrows

### ISSUE THREAD

**Issue by eivrei** [Samfundet/Samfundet#492]
For the topmost and bottom-most job applications the top and bottom arrow shouldn't be visible.

![image](https://user-images.githubusercontent.com/22083159/66185401-9f569f00-e67f-11e9-89d4-570ae0d6ed74.png)

**Comment by hegeaal** [comment]
Priorities values not updating properly.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/48259307/67807616-70bcc000-fa95-11e9-81d5-87c453b2499f.png">

<img width="879" alt="image" src="https://user-images.githubusercontent.com/48259307/67807638-7fa37280-fa95-11e9-8276-3ea08251ccb0.png">

**Comment by eirikvaa** [comment]
Regarding the problem above: This was fixed by updating the gem that handled prioritization.

I am looking into this. I am able to hide the top-most and bottom-most arrows, but when we prioritize a job application, we do this without refreshing the page, and as such the arrows are not updated in their new position.

Before prioritization:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6376002/78348203-efb4a800-75a1-11ea-8bd3-9acc378c5b8d.png">

After prioritization:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6376002/78348218-f80ce300-75a1-11ea-9bd6-2336df23c1c6.png">

To solve this situation, the page must be refreshed. A terribly hack is executing `window.location.reload()` in the `job_applications.js` file:

```javascript
if ($this.hasClass("up")) {
    row.find(".priority").text(priPrev);
    row.prev().find(".priority").text(priCur);
    row.prev().before(row);
} else {
    row.find(".priority").text(priNext);
    row.next().find(".priority").text(priCur);
    row.next().after(row);
}

window.location.reload(); // <-- Added
```

Maybe a better way is just handling this in Rails alone? If we just comment out all the JS code, then Rails is responsible for the `POST` request, but then the view scrolls to the top and you have to scroll to the bottom again. But arrow state is correct.

Or this could just be fixed in JS.

Another improvement we could make is hiding the arrows when there is only one job application. There will be a refresh when the applicant applies to another job, so the state will be updated correctly.

**Comment by evgiz** [comment]
Not worth it, looks OK right now. Gotta clean up some issues man.
