### ISSUE TITLE
Remove corona_flash 

### ISSUE THREAD

**Issue by snorrekr** [Samfundet/Samfundet#907]
The corona_flash system should be removed as it causes informasjon/admin to crash on localhost as well as not being used anymore.

**Comment by nemisis84** [comment]
Removed the corona_flash system, but information/admin still crashes. The problem seems to be that there is a covid-19 page in the db, but when referring to it in views/pages/admin.html.haml it is a NilClass. The solution might be to not create it in the first place when running the seed files in the local setup, but I cannot figure it out.

**Comment by snorrekr** [comment]
As I understood it the flash on the front page is what creates the page without the proper fields. It is not created by the seed files. 
Removing the flash should fix it.
